package com.example.kitchenfairyprototype;

import android.Manifest;
import android.content.Intent;
import android.content.pm.PackageManager;
import android.graphics.Bitmap;
import android.graphics.BitmapFactory;
import android.graphics.Canvas;
import android.graphics.Color;
import android.graphics.Paint;
import android.graphics.pdf.PdfDocument;
import android.os.Bundle;
import android.os.Environment;
import android.view.View;
import android.widget.ArrayAdapter;
import android.widget.ImageView;
import android.widget.ListView;
import android.widget.TextView;
import androidx.appcompat.app.AppCompatActivity;
import androidx.core.app.ActivityCompat;
import com.google.android.material.floatingactionbutton.FloatingActionButton;
import java.io.File;
import java.io.FileOutputStream;
import java.io.IOException;
import java.util.ArrayList;

public class ItemViewer extends AppCompatActivity {

    ArrayAdapter<String> itemAdapter;
    FloatingActionButton itemFab;
    FloatingActionButton fabToList;
    Bitmap bmpLogo, scaledBmpLogo; //for applying the logo to PDFs
    Bitmap recipeImg;
    ItemModel model;
    Bitmap ScaledImg;

    /**
     *ItemViewer onCreate method gets the intent sent with the ItemModel from calling activity
     * Sets the layout to either activity_items_shop for shopping lists
     * or activity_items for recipes.
     * converts the available views depending on which type of ItemModel is sent.
     * */
    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);

        //get intent and import the ItemModel sent by last activity
        Intent i = getIntent();
        Bundle bundle = i.getParcelableExtra("ItemModel_bundle");
        model = (ItemModel) bundle.getSerializable("ItemModel");


        //Shopping objects have a null notes variable.
        if (model.notes == null) {
            setContentView(R.layout.activity_items_shop);

            viewShopping((Shopping) model);
        //if the notes are NOT null, converts to show a Recipe object
        } else {
            setContentView(R.layout.activity_items);
            itemFab = findViewById(R.id.fabItems);
            fabToList = findViewById(R.id.fabToList);

            /*
              onClickListener for the floatingActionButton that creates and saves a pdf document
              */
            itemFab.setOnClickListener(new View.OnClickListener() {
                @Override
                public void onClick(View v) {
                    createPdf(model);

                }
            });


            /*
              onClickListener for the floatingActionButton that sends recipe ingredients to a shopping list
              */
            fabToList.setOnClickListener(new View.OnClickListener() {
                @Override
                public void onClick(View v) {
                    //package the ingredients to be sent via bundle
                    Bundle bundle = new Bundle();
                    bundle.putStringArrayList("ingredients", model.items);
                    //start shopping list editor by intent
                    Intent intent = new Intent(getApplicationContext(), ShopEditor.class);
                    intent.putExtra("ingredient_bundle", bundle);
                    startActivity(intent);
                }
            });

            /*
              The following conditionals check if there is an image to be displayed and sets it up to display
              If the Recipe contains an img, then a Bitmap is generated by converting the byte[] to a Bitmap.
              This is done using the BitByteAdapter.
              */
            if (model.img != null) {
                Bitmap visImg = BitByteAdapter.toBitmap(model.img);
                recipeImg = visImg;
            }

            ImageView img;
            img = findViewById(R.id.itemImg);

            /*
              If there is a recipeImg, then a scaled bitmap is created and set to the ImageView in the activity.
              */
            if (recipeImg != null){
                ScaledImg = Bitmap.createScaledBitmap(recipeImg, 90,90,true);
                img.setImageBitmap(ScaledImg);
            }
            //call viewRecipe to finish setting up the ItemViewer for displaying a Recipe
            viewRecipe((Recipe) model);
        }


        //These two resources are generated for use in the PDF generator createPdf()
        bmpLogo = BitmapFactory.decodeResource(getResources(), R.drawable.kitchen_fairy_circle);
        scaledBmpLogo = Bitmap.createScaledBitmap(bmpLogo, 120, 120, false);



        ActivityCompat.requestPermissions(this,new String[]{
            Manifest.permission.WRITE_EXTERNAL_STORAGE, Manifest.permission.READ_EXTERNAL_STORAGE}, PackageManager.PERMISSION_GRANTED);

    } //end onCreate

    /**
     * converts the ItemViewer for opening a Shopping object
     * gets the ListView for items
     * Sets the list adapter for items
     *
     * */
    //view shopping lists
    public void viewShopping(Shopping model) {
        //find each view to populate. excludes img and notes
        ListView items;
        items = findViewById(R.id.items);
        //set the adapter to fill items
        itemAdapter = new ListViewAdapterCheck(getApplicationContext(), model.items);
        items.setAdapter(itemAdapter);
    }

    /**
     * converts the ItemViewer for opening a Recipe object
     * gets the ListView for items and notes
     * Sets the list adapters for items and notes
     *
     * */
    public void viewRecipe(Recipe model) {
        //find each view to populate.
        ListView items;
        items = findViewById(R.id.items);
        TextView name;
        name = findViewById(R.id.itemName);
        ListView notes;
        notes = findViewById(R.id.notes);

        name.setText(model.name);
        itemAdapter = new ArrayAdapter<>(getApplicationContext(),android.R.layout.simple_list_item_1, model.items);
        items.setAdapter(itemAdapter);
        itemAdapter = new ArrayAdapter<>(getApplicationContext(),android.R.layout.simple_list_item_1, model.notes);
        notes.setAdapter(itemAdapter);
    }

    /**
     * createPdf generates a PDF file containing the information from a recipe passed into the function.
     * creates a pdf canvas and paints the app logo, decorative colors, and text onto the canvas.
     * generates the PDF based on the information that was painted.
     *
     * @param recipe : the recipe to be used to generate the PDF.
     * */
    private void createPdf(ItemModel recipe) {
        String pdfPath = Environment.getExternalStoragePublicDirectory(Environment.DIRECTORY_DOWNLOADS).toString();
        String pdfName = recipe.name + ".pdf";
        File file = new File(pdfPath, pdfName); //replace placeholder with generated string from recipe name

        String name = recipe.name;
        ArrayList<String> ingredients = recipe.items;
        ArrayList<String> instructions = recipe.notes;

        PdfDocument pdfDocument = new PdfDocument();
        Paint pdfPaint = new Paint();

        PdfDocument.PageInfo pageInfo = new PdfDocument.PageInfo.Builder(400,600,1).create();
        PdfDocument.Page page1 = pdfDocument.startPage(pageInfo);

        Canvas canvas = page1.getCanvas();

        int pw = page1.getInfo().getPageWidth();
        int ph = page1.getInfo().getPageHeight();

        pdfPaint.setColor(Color.rgb(219,169,112));
        canvas.drawRect(0,0,pw,35,pdfPaint);
        canvas.drawRect(0,ph - 35,pw,ph,pdfPaint);

        pdfPaint.setColor(Color.rgb(0,0,0));

        pdfPaint.setTextSize(15.0f);
        canvas.drawText(name, 30,70, pdfPaint);
        //set starting Y for ingredients
        pdfPaint.setTextSize(11.0f);
        int Y = 90;
        //print ingredients
        for(String ing : ingredients){
            canvas.drawText(ing, 30, Y, pdfPaint);
            Y += 12;
        }
        //add space
        Y += 20;
        int listNum = 1;
        //print instructions
        for(String ins : instructions){
            String item = listNum + ". " + ins;
            canvas.drawText(item, 30, Y, pdfPaint);
            Y += 14;
            listNum += 1;
        }

        //draw logo
        canvas.drawBitmap(scaledBmpLogo, pw - 130, 10, pdfPaint);


        //Finish page 1
        pdfDocument.finishPage(page1);

        try {
            pdfDocument.writeTo(new FileOutputStream(file));
        } catch (IOException e){
            e.printStackTrace();
        }

        pdfDocument.close();
    }

}
